# _config.yml (Adapted for Cdaprod)
theme: jekyll-theme-chirpy

lang: en
timezone: America/New_York  # Set to your preferred timezone

# SEO settings
title: Cdaprod  # Customize your site title
tagline: Documentation Hub for Cdaprod Projects
description: >-
  A detailed documentation site integrating DevOps, AI, and technical writing projects.

url: "https://ghpages.cdaprod.dev"  # Set to your GitHub Pages URL
baseurl: "/docs"  # Ensure this matches your GitHub Pages folder setting

github:
  username: Cdaprod  # Replace with your GitHub username

twitter:
  username: cdasmktcda  # Replace with your Twitter handle

social:
  name: David Cannan
  email: cdaprod@cdaprod.dev
  links:
    - https://twitter.com/cdasmktcda
    - https://github.com/Cdaprod

# Site verification settings (fill these in if needed)
webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:
  baidu:
  facebook:

# Analytics (fill in your specific provider details)
analytics:
  google:
    id: # Your Google Analytics ID

theme_mode: light  # Choose light or dark mode as your default

avatar: "/assets/images/avatar.png"  # Ensure the avatar path matches your local image
social_preview_image: "/assets/images/social-preview.png"

toc: true  # Enable Table of Contents for posts

# Comments settings (enable if using Disqus, Giscus, etc.)
comments:
  provider: giscus
  giscus:
    repo: Cdaprod/Cdaprod
    repo_id: your_repo_id
    category: your_category
    category_id: your_category_id

paginate: 5  # Adjust pagination settings to suit your needs

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

collections:
  tabs:
    output: true
    sort_by: order

# Exclude files that shouldn’t be part of the build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - docs/tools
  - "*.config.js"
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/